@startuml

TITLE Pull data transfer

participant CONSUMER_S3 as cs3
participant CONSUMER as c
participant PROVIDER as p
participant PROVIDER_S3 as ps3

== TransfertRequestMessage ==

c->p : https://provider.com/transfers/request
note over c
TransferRequestMessage
{
  "@context":  "https://w3id.org/dspace/2024/1/context.json",
  "@type": "dspace:TransferRequestMessage",
  "dspace:consumerPid": "urn:uuid:CONSUMER_PID_TRANSFER",
  "dspace:agreementId": "urn:uuid:e8dc8655-44c2-46ef-b701-4cffdc2faa44",
  "dct:format": "HttpData-PULL",
  "dspace:callbackAddress": "https://......"
}
end note

p->p: Process received message
p->p: store message (agreement will be required later)
p->p: Create TransferProcess with initial consumerPid urn:uuid:PROVIDER_PID_TRANSFER and adds providerPid, state.REQUESTED
p->c: 200 OK, TransferProcess

...PROVIDER "prepare data for exposure"...

== TransferStartMessage ==
p->p: Create TransferStartMessage
group External data
p->p: uses consumerPid and providerPid from TransferProcess to generate DataAddress (download link) \n if the data is stored in and external system

note over p
Base64.encodeBase64URLSafeString(
(urn:uuid:CONSUMER_PID_TRANSFER + "|" + urn:uuid:PROVIDER_PID_TRANSFER)
.getBytes(Charset.forName("UTF-8")));
http://localhost:8080/artifact/encodedValue/1
end note
end
group S3 data
p->p: creates DataAddress from a presignedURL if the data is stored in S3 bucket

note over p
The data will be later downloaded directly from S3,
whereas the external data has to pass through the PROVIDER
end note
end

note over c, p
For the moment (POC) we will exclude logic for adding authorization layer on download link
end note

p->c : callbackUrl + transfers/:consumerPid/start
note right
{
  "@context":  "https://w3id.org/dspace/2024/1/context.json",
  "@type": "dspace:TransferStartMessage",
  "dspace:providerPid": "urn:uuid:PROVIDER_PID_TRANSFER",
  "dspace:consumerPid": "urn:uuid:CONSUMER_PID_TRANSFER",
  "dspace:dataAddress": {
    "@type": "dspace:DataAddress",
    "dspace:endpointType": "https://w3id.org/idsa/v4.1/HTTP",
    "dspace:endpoint": "http://localhost:8080/artifact/encodedValue/1",
  }
}
end note

c->c : process TransferStartMessage, update state locally
c->p : 200 OK
p->p: after 200OK< update state in TransferProcess to SARTED

...Consumer executes download link...

== Consumer fetches data ==

group External data
c->p ++: http://localhost:8080/artifact/encodedValue/1 (DataAddress)
note right
This can be performed in EndpointAvailableFilter
end note
p->p: decode encoded value
p->p: checks TransferProcess for given consumerPid and providerPid if state is STARTED
p->p: for consumerPid and providerPid get agreementId (TransferRequestMessage)
p->p: validate if agreement is valid
return download artifact
c->cs3 : upload artifact to S3 bucket
end

group S3 data
c->ps3 ++: http://localhost:9000/dsp-true-connector-provider-bucket/urn%3Auuid%3A71053997-02f8-4def-b445-a6b9ce5a1d18 (DataAddress)
ps3->ps3: performs checks
return download artifact
ps3->cs3 : upload artifact to S3 bucket
end
@enduml