package it.eng.dcp.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Persisted Issuer-side credential request record.
 *
 * Represents a request created when a Holder requests one or more credentials from an Issuer.
 */
@Document(collection = "credential_requests")
@Getter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CredentialRequest {

    @Id
    private String id;

    /**
     * Issuer-side identifier for this issuance request (may be exposed in /requests status).
     *
     * This ID is generated by the Issuer when the request is stored.
     */
    private String issuerPid;

    /**
     * Holder identifier provided in the incoming request (often a DID or holderPid).
     *
     * The Holder PID is supplied in the CredentialRequestMessage and is used to correlate issuance.
     */
    private String holderPid;

    /**
     * List of credential object ids requested (references into credentialsSupported).
     * Each id references an entry in the Issuer's credentialsSupported list.
     */
    private List<String> credentialIds = new ArrayList<>();

    /**
     * Current status of the request (PENDING/ISSUED/REJECTED).
     */
    private CredentialStatus status = CredentialStatus.PENDING;

    private String rejectionReason;

    private Instant createdAt = Instant.now();

    public static CredentialRequest fromMessage(CredentialRequestMessage msg) {
        CredentialRequest req = new CredentialRequest();
        req.id = "req-" + UUID.randomUUID();
        req.issuerPid = req.id;
        req.holderPid = msg.getHolderPid();
        if (msg.getCredentials() != null) {
            for (var cr : msg.getCredentials()) {
                req.credentialIds.add(cr.getId());
            }
        }
        req.status = CredentialStatus.PENDING;
        req.createdAt = Instant.now();
        return req;
    }

    @JsonPOJOBuilder(withPrefix = "")
    public static class Builder {
        private final CredentialRequest req;

        private Builder() {
            req = new CredentialRequest();
        }

        public static Builder newInstance() {
            return new Builder();
        }

        public Builder issuerPid(String issuerPid) {
            req.issuerPid = issuerPid;
            return this;
        }

        public Builder holderPid(String holderPid) {
            req.holderPid = holderPid;
            return this;
        }

        public Builder credentialIds(java.util.List<String> credentialIds) {
            if (credentialIds != null) {
                req.credentialIds.clear();
                req.credentialIds.addAll(credentialIds);
            }
            return this;
        }

        public Builder status(CredentialStatus status) {
            req.status = status;
            return this;
        }

        public Builder rejectionReason(String reason) {
            req.rejectionReason = reason;
            return this;
        }

        public Builder createdAt(Instant createdAt) {
            req.createdAt = createdAt;
            return this;
        }

        public CredentialRequest build() {
            // minimal validation: holderPid required and credentialIds non-empty
            if (req.holderPid == null || req.holderPid.isBlank()) {
                throw new jakarta.validation.ValidationException("CredentialRequest - holderPid is required");
            }
            if (req.credentialIds == null || req.credentialIds.isEmpty()) {
                throw new jakarta.validation.ValidationException("CredentialRequest - at least one credential id is required");
            }
            if (req.id == null) {
                req.id = "req-" + java.util.UUID.randomUUID();
            }
            if (req.issuerPid == null) req.issuerPid = req.id;
            if (req.createdAt == null) req.createdAt = Instant.now();
            if (req.status == null) req.status = CredentialStatus.PENDING;
            return req;
        }
    }
}
