package it.eng.dcp.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import it.eng.dcp.common.model.BaseDcpMessage;
import it.eng.tools.model.DSpaceConstants;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import jakarta.validation.ValidationException;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@JsonDeserialize(builder = CredentialRequestMessage.Builder.class)
@Getter
@NoArgsConstructor(access = lombok.AccessLevel.PRIVATE)
public class CredentialRequestMessage extends BaseDcpMessage {

    @Serial
    private static final long serialVersionUID = 1L;

    @Override
    @JsonProperty(value = DSpaceConstants.TYPE, access = JsonProperty.Access.READ_ONLY)
    public String getType() {
        return CredentialRequestMessage.class.getSimpleName();
    }

    // Optional request identifier generated by Holder (client) to correlate issuance flow
    private String requestId;

    @NotNull
    private String holderPid;

    @NotNull
    @Size(min = 1)
    private List<CredentialReference> credentials = new ArrayList<>();

    @JsonPOJOBuilder(withPrefix = "")
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Builder {
        private final CredentialRequestMessage msg;

        private Builder() {
            msg = new CredentialRequestMessage();
            msg.getContext().add(DSpaceConstants.DCP_CONTEXT);
        }

        @JsonCreator
        public static Builder newInstance() {
            return new Builder();
        }

        @JsonProperty(DSpaceConstants.CONTEXT)
        public Builder context(List<String> context) {
            if (context != null) {
                msg.getContext().clear();
                msg.getContext().addAll(context);
            }
            return this;
        }

        public Builder requestId(String requestId) {
            msg.requestId = requestId;
            return this;
        }

        public Builder holderPid(String holderPid) {
            msg.holderPid = holderPid;
            return this;
        }

        @JsonProperty("credentials")
        public Builder credentials(List<CredentialReference> credentials) {
            if (credentials != null) {
                msg.credentials.clear();
                msg.credentials.addAll(credentials);
            }
            return this;
        }

        public CredentialRequestMessage build() {
            try {
                msg.validateBase();
                if (msg.credentials == null) {
                    msg.credentials = new ArrayList<>();
                }
                return msg;
            } catch (Exception e) {
                throw new ValidationException("CredentialRequestMessage - " + e.getMessage());
            }
        }
    }

    @JsonDeserialize(builder = CredentialReference.Builder.class)
    @NoArgsConstructor(access = lombok.AccessLevel.PRIVATE)
    @Getter
    public static class CredentialReference implements java.io.Serializable {

        @Serial
        private static final long serialVersionUID = 1L;

        @NotNull
        private String id;

        @JsonPOJOBuilder(withPrefix = "")
        @JsonIgnoreProperties(ignoreUnknown = true)
        public static class Builder {
            private final CredentialReference ref;

            private Builder() {
                ref = new CredentialReference();
            }

            public static Builder newInstance() {
                return new Builder();
            }

            public Builder id(String id) {
                ref.id = id;
                return this;
            }

            public CredentialReference build() {
                try (jakarta.validation.ValidatorFactory vf = jakarta.validation.Validation.buildDefaultValidatorFactory()) {
                    java.util.Set<jakarta.validation.ConstraintViolation<CredentialReference>> violations = vf.getValidator().validate(ref);
                    if (violations.isEmpty()) {
                        return ref;
                    }
                    throw new jakarta.validation.ValidationException("CredentialReference - " +
                            violations.stream().map(v -> v.getPropertyPath() + " " + v.getMessage()).collect(Collectors.joining(",")));
                }
            }
        }
    }
}
