services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    networks:
      - dsp-tc-net
    volumes:
      - mongodb-data:/data/db
      - mongodb-configdb:/data/configdb

  rustfs:
    image: rustfs/rustfs:1.0.0-rc.6
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
    environment:
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    networks:
      - dsp-tc-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 20s
      retries: 3

  dsp-tc-connector:
    image: ghcr.io/engineering-research-and-development/dsp-true-connector:test
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    logging:
      options:
        max-size: "200M"
    container_name: dsp-tc-connector
    ports:
      - 0.0.0.0:8888:2222 #FTP
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - dsp-tc-net
    environment:
      - "JDK_JAVA_OPTIONS=-Xmx1024m"
      - SPRING_PROFILES_ACTIVE=tck
      - BASE_URL=${CONNECTOR_A_BASE_URL}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KEYSTORE_ALIAS=${KEYSTORE_ALIAS}
      - TRUSTSTORE_NAME=${TRUSTSTORE_NAME}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
    volumes:
      - ./connector_tck_resources:/config
      - ./tc_cert:/cert
      - ./:/home/nobody/ftp
      - tc_log:/var/log/tc

volumes:
  mongodb-data:
  mongodb-configdb:
  rustfs_data:
  tc_log:

networks:
  dsp-tc-net:
    driver: bridge
    name: dsp-tc-net
