package it.eng.dcp.service;

import it.eng.dcp.config.CredentialMetadataConfig;
import it.eng.dcp.config.DcpProperties;
import it.eng.dcp.model.IssuerMetadata;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CredentialMetadataServiceTest {

    @Mock
    private DcpProperties dcpProperties;

    @Mock
    private CredentialMetadataConfig credentialMetadataConfig;

    private CredentialMetadataService service;

    @BeforeEach
    void setUp() {
        service = new CredentialMetadataService(dcpProperties, credentialMetadataConfig);
    }

    @Test
    void buildIssuerMetadata_withConfiguredCredentials_success() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        
        CredentialMetadataConfig.CredentialConfig config = new CredentialMetadataConfig.CredentialConfig();
        config.setId("test-id-123");
        config.setType("CredentialObject");
        config.setCredentialType("MembershipCredential");
        config.setCredentialSchema("https://example.com/schemas/membership.json");
        config.setBindingMethods(List.of("did:web", "did:key"));
        config.setProfile("vc11-sl2021/jwt");

        List<CredentialMetadataConfig.CredentialConfig> configs = List.of(config);
        when(credentialMetadataConfig.getSupported()).thenReturn(configs);

        // Act
        IssuerMetadata result = service.buildIssuerMetadata();

        // Assert
        assertNotNull(result);
        assertEquals("did:web:localhost:8090", result.getIssuer());
        assertEquals(1, result.getCredentialsSupported().size());
        
        IssuerMetadata.CredentialObject credential = result.getCredentialsSupported().get(0);
        assertEquals("test-id-123", credential.getId());
        assertEquals("CredentialObject", credential.getType());
        assertEquals("MembershipCredential", credential.getCredentialType());
        assertEquals("https://example.com/schemas/membership.json", credential.getCredentialSchema());
        assertEquals(2, credential.getBindingMethods().size());
        assertEquals("vc11-sl2021/jwt", credential.getProfile());
    }

    @Test
    void buildIssuerMetadata_noCredentialsConfigured_throwsException() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        when(credentialMetadataConfig.getSupported()).thenReturn(new ArrayList<>());

        // Act & Assert
        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> service.buildIssuerMetadata());

        assertTrue(exception.getMessage().contains("No credentials configured"));
        assertTrue(exception.getMessage().contains("dcp.credentials.supported"));
    }

    @Test
    void buildIssuerMetadata_withDefaultConnectorDid_logsWarning() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn(null);
        
        CredentialMetadataConfig.CredentialConfig config = new CredentialMetadataConfig.CredentialConfig();
        config.setCredentialType("TestCredential");
        
        when(credentialMetadataConfig.getSupported()).thenReturn(List.of(config));

        // Act
        IssuerMetadata result = service.buildIssuerMetadata();

        // Assert
        assertNotNull(result);
        assertEquals("did:web:issuer-url", result.getIssuer());
    }

    @Test
    void buildIssuerMetadata_withAutoGeneratedId_success() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        
        CredentialMetadataConfig.CredentialConfig config = new CredentialMetadataConfig.CredentialConfig();
        // No ID set - should be auto-generated
        config.setCredentialType("TestCredential");
        
        when(credentialMetadataConfig.getSupported()).thenReturn(List.of(config));

        // Act
        IssuerMetadata result = service.buildIssuerMetadata();

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getCredentialsSupported().size());
        
        IssuerMetadata.CredentialObject credential = result.getCredentialsSupported().get(0);
        assertNotNull(credential.getId());
        assertFalse(credential.getId().isBlank());
    }

    @Test
    void buildIssuerMetadata_withDefaultProfile_success() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        when(dcpProperties.getSupportedProfiles()).thenReturn(List.of("VC11_SL2021_JWT", "VC11_SL2021_JSONLD"));
        
        CredentialMetadataConfig.CredentialConfig config = new CredentialMetadataConfig.CredentialConfig();
        config.setCredentialType("TestCredential");
        // No profile set - should use first from supported profiles
        
        when(credentialMetadataConfig.getSupported()).thenReturn(List.of(config));

        // Act
        IssuerMetadata result = service.buildIssuerMetadata();

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getCredentialsSupported().size());
        assertEquals("vc11-sl2021/jwt", result.getCredentialsSupported().get(0).getProfile());
    }

    @Test
    void buildIssuerMetadata_withDefaultBindingMethods_success() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        
        CredentialMetadataConfig.CredentialConfig config = new CredentialMetadataConfig.CredentialConfig();
        config.setCredentialType("TestCredential");
        // No binding methods set - should use default
        
        when(credentialMetadataConfig.getSupported()).thenReturn(List.of(config));

        // Act
        IssuerMetadata result = service.buildIssuerMetadata();

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getCredentialsSupported().size());
        assertEquals(List.of("did:web"), result.getCredentialsSupported().get(0).getBindingMethods());
    }

    @Test
    void buildIssuerMetadata_invalidCredentialConfig_throwsException() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        
        CredentialMetadataConfig.CredentialConfig config = new CredentialMetadataConfig.CredentialConfig();
        // Missing credentialType - should fail validation
        config.setId("test-id");
        
        when(credentialMetadataConfig.getSupported()).thenReturn(List.of(config));

        // Act & Assert
        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> service.buildIssuerMetadata());

        assertTrue(exception.getMessage().contains("Failed to build any valid credentials"));
    }

    @Test
    void buildIssuerMetadata_multipleCredentials_success() {
        // Arrange
        when(dcpProperties.getConnectorDid()).thenReturn("did:web:localhost:8090");
        
        CredentialMetadataConfig.CredentialConfig config1 = new CredentialMetadataConfig.CredentialConfig();
        config1.setCredentialType("MembershipCredential");
        config1.setCredentialSchema("https://example.com/schemas/membership.json");
        
        CredentialMetadataConfig.CredentialConfig config2 = new CredentialMetadataConfig.CredentialConfig();
        config2.setCredentialType("CompanyCredential");
        config2.setCredentialSchema("https://example.com/schemas/company.json");
        
        when(credentialMetadataConfig.getSupported()).thenReturn(List.of(config1, config2));

        // Act
        IssuerMetadata result = service.buildIssuerMetadata();

        // Assert
        assertNotNull(result);
        assertEquals(2, result.getCredentialsSupported().size());
        assertEquals("MembershipCredential", result.getCredentialsSupported().get(0).getCredentialType());
        assertEquals("CompanyCredential", result.getCredentialsSupported().get(1).getCredentialType());
    }
}

