server.port=9091
spring.application.name=data-plane-http-push
spring.data.mongodb.uri=mongodb://localhost:27017/data-plane-push
dataplane.endpoint=http://localhost:9091
dataplane.control-plane-admin-endpoint=http://localhost:8080
dataplane.auth-type=API_KEY
dataplane.api-key=changeme
dataplane.control-plane-admin-secret=${DATAPLANE_CONTROL_PLANE_ADMIN_SECRET:}
s3.endpoint=http://minio:9000
s3.accessKey=minioadmin
s3.secretKey=minioadmin
s3.region=us-east-1
s3.bucketName=provider-bucket
server.ssl.enabled=false
