services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-configdb:/data/configdb

  localstack:
    container_name: localstack
    image: localstack/localstack:4.3.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3,iam,sts
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=accessKeyChangeIt
      - AWS_SECRET_ACCESS_KEY=secretKeyChangeIt
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongodb-data:
  mongodb-configdb:
  localstack_data:
